# Generated by Django 3.0.5 on 2020-12-20 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=90, unique=True)),
                ('firstName', models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(1)])),
                ('lastName', models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(1)])),
                ('email', models.CharField(max_length=90, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('password', models.CharField(max_length=90, validators=[django.core.validators.MinLengthValidator(9)])),
            ],
        ),
    ]
